# Generated by Django 4.1.6 on 2023-02-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='Men',
        ),
    ]
